services:
  - type: web
    name: kavach-api
    runtime: python
    rootDir: landslide/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /

  - type: web
    name: kavach-frontend
    runtime: static
    rootDir: landslide/frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://kavach-api-4tdx.onrender.com
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
